# Generated by Django 3.1 on 2020-10-28 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.payment')),
            ],
        ),
    ]
