# Generated by Django 3.1 on 2020-11-13 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201113_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='core.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ManyToManyField(blank=True, to='core.Discount'),
        ),
    ]
