# Generated by Django 3.1 on 2020-09-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=255)),
                ('suburb', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('AKL', 'Auckland'), ('WELL', 'Wellington'), ('CHC', 'Christchurch')], default='AKL', max_length=4)),
                ('country', models.CharField(default='New Zealand', max_length=100)),
                ('postcode', models.IntegerField()),
            ],
        ),
    ]
