# Generated by Django 3.1 on 2020-09-03 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ecommerce_app.user')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.address')),
            ],
        ),
    ]
