# Generated by Django 3.1 on 2020-09-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('image', models.ImageField(null=True, upload_to='')),
                ('description', models.TextField(blank=True)),
                ('category', models.ManyToManyField(to='ecommerce_app.Category')),
                ('discount', models.ManyToManyField(to='ecommerce_app.Discount')),
            ],
        ),
    ]
