# Generated by Django 3.1 on 2020-09-04 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ecommerce_app.order')),
                ('quantity', models.IntegerField()),
                ('product', models.ManyToManyField(to='ecommerce_app.Product')),
            ],
        ),
    ]
