# Generated by Django 3.1 on 2020-09-03 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0005_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ecommerce_app.payment')),
            ],
        ),
    ]
