# Generated by Django 3.1 on 2020-09-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0010_auto_20200912_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
