# Generated by Django 3.1 on 2020-09-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0011_auto_20200912_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ManyToManyField(blank=True, to='ecommerce_app.Discount'),
        ),
    ]
