# Generated by Django 3.1 on 2020-08-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='country',
            field=models.CharField(default='New Zealand', editable=False, max_length=30),
        ),
    ]
