# Generated by Django 3.1 on 2020-08-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20200812_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='street_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
