# Generated by Django 3.1 on 2020-08-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_auto_20200812_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='street_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='university',
            name='street_number',
            field=models.IntegerField(blank=True),
        ),
    ]
